### ISSUE TITLE
One of the sensors is not working

### ISSUE THREAD

**Issue by nununo** [nununo/pyVela2017#105]

**Comment by tmontes** [comment]
Progress:
* Checked all wirings.
* Measured resistance across most connections.
* Confirmed one of the sensors shows different resistance readings.

Conclusion:
* Not really sure.
* Both sensors now produce input: albeit with one driving higher values than the other.

Did we have a mis-contact somewhere?

Closing with the hope that this doesn't come back and haunt us! :)
