### ISSUE TITLE
Review code for consistency (naming, etc)

### ISSUE THREAD

**Issue by nununo** [nununo/pyVela2017#23]

**Comment by tmontes** [comment]
Tasks:
- [x] Naming consistency and singulars vs. plurals:
  - [x] Packages and modules.
  - [x] Classes and methods.
  - [x] Variables and attributes.
- [x] Comments and docstrings: spelling, grammar + still in sync with the code?
- [x] Linting.
- [x] Remove the no-longer-used `_INPUT_SIZE` module global from `inputs/arduino/input.py`.
