### ISSUE TITLE
Setup PI as an access point

### ISSUE THREAD

**Issue by nununo** [nununo/pyVela2017#26]

**Comment by tmontes** [comment]
Short update:
* Tested guide at https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md.
* Worked fine.
* Adding an entry to /etc/hosts with the static WLAN IP and a hostname will be useful.
* Important: no need (actually shouldn't) to setup additional routing + masquerading. This is supposed to work as an isolated and standalone network.

**Comment by tmontes** [comment]
Completed successfully.

**Comment by tmontes** [comment]
PS: Nuno's PI was still running Jessie, procedure needed minor adjustments.

https://cdn-learn.adafruit.com/downloads/pdf/setting-up-a-raspberry-pi-as-a-wifi-access-point.pdf
