### ISSUE TITLE
Plot arduino input level thresholds along with actual readings.

### ISSUE THREAD

**Issue by tmontes** [nununo/pyVela2017#27]

**Comment by tmontes** [comment]
Note:
* We're currently plotting raw arduino readings.
* Level triggering is, however, based on thresholds for the aggregated derivative calculation.

Thus:
* If we plot the thresholds, we'll be comparing apples to oranges...
* ...unless, of course, we plot the aggregate derivative instead.

More:
* Plotting the aggregated derivative in addition to the raw values will probably lead to readability problems, given the former is in the, say, 0-30 range, and the latter in the ~500 range...
* ...unless we use a vertical logarithmic scale on the chart, of course! (not sure it's a great idea)

Comments?

**Comment by nununo** [comment]
Maybe we don't need to plot the sensor values at all and instead should stick to the aggregate derivative which is, after all, what triggers the thresholds. Or, if we still need the sensor data, we can plot both side by side and not overlapped.

**Comment by tmontes** [comment]
...or maybe on different scenes on the same chart, for the sake of screen space?

I seem to remember that to be possible with [chartjs](http://www.chartjs.org).

**Comment by nununo** [comment]
Even better!

**Comment by tmontes** [comment]
WRT to my previous comment: s/scenes/scales/, that's what I meant.

(where s/this/that/ is to be understood as "replace this with that", in the good old UNIX tradition) ;-)

**Comment by tmontes** [comment]
I've got some progress on this: now plotting RAW and AGD sensor readings on independent axes. Bonus: each independently togglable (not that I coded it, it comes "free" with chartjs).

Wiring adaptation depends on the open PRs #45, #46 and #47, though (well, not on the last one!). ~~So it's holding here https://github.com/tmontes/pyVela2017/tree/pending-enhanced-chart~~

**Comment by nununo** [comment]
All the PRs it depends on now merged ;)

**Comment by tmontes** [comment]
Sharing a few thoughts:
* This is nearly done.
* All that is left is for the Arduino sensor input to *send* its thresholds to the web client.
* This brings up a few "wiring" related questions:
  * We could use the same `raw_data_callable`, passing in an appropriate `type`; instead of adding it in the web socket server, we could just validate its presence before actually sending.
  * I like this simple idea: after all, "raw" can be as "raw" as needed and still be "clean" (because its "raw"!).
  * The problem with this approach is:
    * The best Arduino sensor input can do is send the threshold values on start (and, with #28, whenever they change).
    * However, we need to push these values every time a new web socket client connects, otherwise they'll see no threshold annotations.
  * Possible solutions:
    * Add a new `raw_something_callable` wiring? (don't like the idea much)
    * Add a "remember_this" / "resend_on_connect" / "this_one_is_really_important" flag to existing raw data pushes? This would have the web socket server remember whichever *raws* it got flagged like so, sending them on each new client connection.

More thoughts? :)
