### ISSUE TITLE
Re-design DBus session dependency

### ISSUE THREAD

**Issue by tmontes** [nununo/pyVela2017#37]
Current scenario:
* `candle2017.py` checks for the `DBUS_SESSION_BUS_ADDRESS` variable in the environment.
* If not present, it respawns itself under `dbus-run-session`.

Observation:
* The self-respawning is not very elegant.
* Due to intrinsic `dbus-run-session` limitations, this leads to somewhat inelegant clean stops.

Idea (after a little investigation):
* Let's forget about `dbus-run-session` and use `dbus-damon` directly instead.
* Maybe `player/dbus_manager.py` can handle it all:
  * Spawns (configurable) `dbus-daemon` with the `--session` and `--print-address` flags.
  * Tracks the bus address output and adds it to the environment.
  * Which will be ready for all the players after player manager launches them.
  * It will need a `stop` method to stop the spawned `dbus-daemon`.
* Player manager will need to stop DBus manager after cleaning up all processes.

Benefits:
* Much cleaner and easier to grasp design.
* Simpler system level integration.

Efforts:
* Not much.
* Need to confirm out-of-control process failure scenarios are still handled properly.

**Comment by nununo** [comment]
If you say so LOL
