### ISSUE TITLE
Review README.md

### ISSUE THREAD

**Issue by tmontes** [nununo/pyVela2017#40]
Including:
- [x] Spell check it (noted in *Raspberri* which should be *Raspberry*).
- [x] Improve development notes or create a separate document and link to it.
- [x] Review the configuration section: `inputs.agd.source` is outdated.
- [x] Rewrite / improve the introduction: the first section should describe the experience.
- [x] Update the **Running** section to mention that a `dbus-daemon` process should also be running.

**Comment by tmontes** [comment]
PR #72 addresses the first and the last items above.

**Comment by tmontes** [comment]
PR #77 addresses all open checkboxes with the exception of "Improve development notes or create a separate document and link to it".

**Comment by nununo** [comment]
fixed by #90
