### ISSUE TITLE
Arduino input sensor: more efficient aggregated derivative calculation?

### ISSUE THREAD

**Issue by tmontes** [nununo/pyVela2017#49]
* Currently using a `collections.deque()` to track the most recent `_INPUT_SIZE` readings.
* On every new sensor reading:
  * The deque is updated.
  * The aggregated derivative is calculated from scratch, iterating the whole deque.

* This is computationally intensive and non-scalable (memory and processor-wise).

* Thoughts:
  * With the current algorithm I don't think we can send the deque away.
  * But maybe we can avoid iterating through it every time by tracking the "current aggregated derivative" (call it `current_agd`), incrementally updating it as in:
    * If reading is zero, set `current_agd` to 0 and clear the deque().
    * Otherwise, add reading to `current_agd` and, if len(deque) == `_INPUT_SIZE`, subtract its oldest value from `current_agd`; then append the reading to the deque().
  * This speeds up the calculation and makes it almost O(1) instead of the current O(n) (clearing the deque not O(1), but certainly much faster than our current approach; the other deque operations are O(1): len() and getting the oldest item).

PS: Not that we desperately need those CPU cycles, though. :)

**Comment by nununo** [comment]
This was implemented in #71 but ended up rejected because the trade off for a small optimization was extra complexity. Not worth it.
