### ISSUE TITLE
Move webserver into into inputs?

### ISSUE THREAD

**Issue by tmontes** [nununo/pyVela2017#56]
I'm in a "make things simpler and with less code" tonic...

**Preamble**

I have a WIP branch that simplifies the webserver by quite a bit: it mostly throws the `http` module away and handles everything in what has been the `websocket` module to date (but renamed to `server` on that branch).

The benefits are:
* There is a single HTTP endpoint serving both HTML *and* the websocket protocol.
* The javascript client can then, easily, connect back without needing a hardcoded a TCP port.
* This makes webserver configuration (port and interface) possible and trivial.
* Again, less code.

That branch is holding on #55 which imposed other types of simplifying changes to `websocket.py`.

**Result**

With such a simpler *and* now easily configurable web server, maybe we can move it to the `inputs` package and take advantage of its ability to "setup" inputs based on the `settings.json` configuration.

While the webserver is not strictly an "input", I think it fits nicely along with the other inputs.

Thoughts?

**Comment by nununo** [comment]
Wow! Love it.

**Comment by nununo** [comment]
implemented in #58
