### ISSUE TITLE
Improve input architecture

### ISSUE THREAD

**Issue by tmontes** [nununo/pyVela2017#60]
Status quo:
* Input manager calls "arbitrary" functions to initialize each input: somewhat messy.
* It also isn't ready to "finalize" inputs.
* More: if input initialization were to be asynchronous, input manager wouldn't know how to handle it.

Idea:
* Create a "base input class" with two methods "initialize" and "cleanup" (or some such).
* Re-factor each existing input into a derived class.
* Adjust input manager to account for that.

Once done:
* Call "input manager" cleanup on stop (this will be more important once I share a crazy idea I've been secretly exploring: having a microphone based input) ;)

TEASER: https://github.com/tmontes/pyVela2017/blob/xplore-asla-input/inputs/alsaaudio/README.md

**Comment by nununo** [comment]
oh mon dieu!

**Comment by nununo** [comment]
Closed by #61
