### ISSUE TITLE
Level triggering mis-behaviour

### ISSUE THREAD

**Issue by tmontes** [nununo/pyVela2017#74]
With the change in 074fbbe796c5b2b097d909358fb58242d4e9d19e (argh, a PR would definitely have been cleaner!) the following sequence is now possible:

- Input stable, with AGD output stable: level=0.
- Input raises such that AGD triggers level=1.
- While level 1 is playing:
  - Input goes down such that AGD triggers level=0.
  - Player manager forces a cross-fade from level=1 to level=0.

The last step does not make sense:
- Level 0 is "always there" so fading it feels silly.
- Going back to level 0 (rest) should always act naturally and not be forced ahead of time.

Possible fixes:
- Have AGD *not* trigger changes to level 0.
- Have player manager ignore changes to level 0.

**Comment by tmontes** [comment]
The fix at the player manager level feels more solid and consistent:
* This is the code that has changed, AGD always triggered changes to level 0.
* By having player manager handle that, future inputs triggering premature changes to level 0 will also be handled.

Thoughts?

**Comment by nununo** [comment]
fixed by #76
