### ISSUE TITLE
Multiple triggers of same level need fixing

### ISSUE THREAD

**Issue by nununo** [nununo/pyVela2017#93]

**Comment by nununo** [comment]
```
I 30.080 player.mngr new_level=2 comment='web'
I 30.088 player.each.c.p2-03-88 fade in starting
I 31.151 player.each.c.p2-03-88 fade in completed
I 31.463 player.mngr new_level=2 comment='web'
I 31.469 player.each.c.p2-03-88 fade out starting
I 31.496 player.each.c.p2-03-88 fade in starting
I 32.528 player.each.c.p2-03-88 fade out completed
I 32.530 player.each.c.p2-03-88 stopping
C 32.596 twisted.internet.defer Unhandled error in Deferred:
C 32.599 twisted.internet.defer 
I 32.607 player.proc.c.p2-03-88 process ended, exit code 0
I 32.609 player.mngr player level=2 ended
I 32.611 player.mngr creating player level=2
I 32.613 player.each.c.p2-03-51 spawning
I 32.623 player.proc.c.p2-03-51 process started, PID 2948
I 32.630 player.each.c.p2-03-88 stopped
I 32.948 player.each.c.p2-03-51 ready
```
The same player is simultaneously fading in and fading out resulting in a flickering effect.

**Comment by tmontes** [comment]
Sharing a few thoughts on possible solutions.

### Easy one
* On same level re-triggers, just re-wind the current player.
* Need to take care in re-scheduling the auto fade out.
* Trade-offs:
  * Continuous re-triggers keep re-starting the same video file.
  * Non-cross-faded transition may be visually unappealing.

### Better one
(kind of crazy, not sure if possible, but resource-efficient)
* Merge the current per-video-level files into a single, per-level file, where each different clip is a different video chapter.
* Keep two omxplayers per level.
* Be clever enough to:
  * Select a random video chapter each time playing is requested.
  * Determine that chapter's duration to account for auto fade out scheduling.
* Whenever there's a same level re-trigger, cross fade to the other omxplayer in the same level.
* Addresses the trade-offs in the "Easy one" solution.
* Trade-offs:
  * Needs the video files to be re-worked.
  * More complex logic and code.
  * Not sure if it is possible to ask omxplayer for a given chapter's duration.

### Another one
* Keep several omxplayers per level (not sure how many, maybe 2-5?).
* On-retrigger, cross-fade to a different omxplayer of the same level.
* Addresses the trade-offs in the "Easy one" solution.


Final notes:
* Any possible solution should prevent the same level re-trigger rate (10 re-triggers per second would certainly result in unpleasant/unnatural video playing).
* Solutions involving same level cross-fades will need to take the omxplayer's "visual layer" into account: not clear how, yet.
* Solutions will need to account for the possibility that a scheduled fade out is occurring when the re-triggering takes place.

**Comment by tmontes** [comment]
PS: I have a branch with the "Easy one" solution implemented. I just do not have video output on the PI to evaluate whether the non-cross-faded video rewind transition feels any good. :)

PPS: It also does not currently limit the re-trigger rate.

**Comment by tmontes** [comment]
@nununo 

Played a bit with the "easy one" implementation while plugged to an actual video output.
OMXPlayer seems to stall for a split-second on rewind... :-/

I'll submit that as a PR to make it easy for you to try it out: my initial feeling is we'll need to take a different approach. You'll have the final word, of course.

**Comment by tmontes** [comment]
Extra information as an "interesting fact":

Manually launching OMXPlayer and then speeding the video up (with the "." key) seems to make rewinding smoother. So .......maybe.......:
* If the video files are rendered, say, at 1/4th the speed.
* If we ask each player to play at 4x the speed (no command line option, unfortunately, needs to be done with a DBus command)
* Then the rewinding thing may avoid the split-second stall.

**Comment by tmontes** [comment]
Following up on the "interesting fact" mentioned above:
* Maybe the video playback stalls for a split second on rewind because it needs to find a certain amount of key frames before actually updating the output (based on a very rough idea of H.264 encoding).
* If that is the case, rewinding may behave better if the encoded video has a higher keyframe density.

UPDATE:
* Re-enconded a few files with more I-Frame density.
* OMXPlayer playback still stalls for a split-second on rewind.
* Tried 100% I-Frames, even at 120fps: no go. OMXPlayer still stalls.
* Fluid rewind still seems to be achieved with 4x playback speed, regardless of video encoding details (requiring videos rendered @1/4th the speed).
* Argh!

**Comment by tmontes** [comment]
More facts:
* Mplayer does not stall when rewinding the videos.
* We've apparently facing an OMXPlayer limitation.

**Comment by tmontes** [comment]
After testing even more, I opened an issue here https://github.com/popcornmix/omxplayer/issues/618

**Comment by tmontes** [comment]
Possible solution:
* Keep more than one player per (relevant) level: a fifo?
* On re-trigger, stop the currently playing clip and immediately start the next clip in the fifo with no x-fade / fade-in.
