### ISSUE TITLE
Reconsider: trigger level 1 while playing level 2 clips?

### ISSUE THREAD

**Issue by tmontes** [nununo/pyVela2017#99]
While working on #93, I stumbled upon a behaviour I think might need to be reviewed:
* Recent changes to `player_manager` allow triggering a level 1 clip while a level 2 clip is playing.
* Given the nature of the clips we've been using, I think this leads to strange, unnatural responses.

**Comment by nununo** [comment]
Reconsidered: level N-1 will not trigger while playing level N.
